const actions = module.exports = [];
actions.setCurrentTrack = track => ({ type: 'SET_CURRENT_TRACK', payload: track });
actions.clearCurrentTrack = () => ({ type: 'CLEAR_CURRENT_TRACK' });
actions.clearCurrentAlbum = () => ({ type: 'CLEAR_CURRENT_ALBUM' });
actions.setCurrentAlbum = album => ({ type: 'SET_CURRENT_ALBUM', payload: album });
actions.setCurrentPlaylist = playlist => ({ type: 'SET_CURRENT_PLAYLIST', payload: playlist });
actions.setCurrentPlaylistTracks = tracks => ({ type: 'SET_CURRENT_PLAYLIST_TRACKS', payload: tracks });
actions.clearCurrentPlaylist = () => ({ type: 'CLEAR_CURRENT_PLAYLIST' });
actions.setMode = mode => ({ type: 'SET_CURRENT_MODE', payload: mode });
actions.setSearch = search => ({ type: 'SET_SEARCH', payload: search });
